apiServer:
  certSANs:
  - 121.190.0.187
  - 192.168.56.2
  - 127.0.0.1
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.18.20
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler:
  extraArgs:
    leader-elect: "false"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-20T13:11:31Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "197"
  uid: 32d6b451-3f53-4e21-8b2f-c2822dc248e0
