apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tekton-pipelinerun
spec:
  pipelineRef:
    name: tekton-pipeline
  params:
  - name: tag
    value: "v1.0" # Thay "v1.0" bằng tag cụ thể mà bạn muốn sử dụng
  # Phần còn lại của cấu hình
  workspaces:
  - name: pipeline-shared-data
  - name: kubeconfig-dir
  params:
  - name: tag
    type: string
    description: Docker image tag
  tasks:
  - name: clone-repository
    taskRef:
      kind: Task
      name: git-clone
    params:
    - name: url
      value: "https://github.com/StatisticsFox/opens_Team10.git"
    - name: revision
      value: "main"
    - name: deleteExisting
      value: "true"
    workspaces:
    - name: output
      workspace: pipeline-shared-data

  - name: build-image
    taskRef:
      kind: Task
      name: jib-gradle
    runAfter:
    - clone-repository
    params:
    - name: IMAGE
      value: "zxcvb5434/devopstest:$(params.tag)"
    workspaces:
    - name: source
      workspace: pipeline-shared-data

  - name: kubectl-deploy
    taskRef:
      kind: Task
      name: kubectl-deploy
    runAfter:
    - build-image
    params:
    - name: TAG
      value: "$(params.tag)"
    - name: YAMLFILE
      value: "./k8s/deployment.yaml"
    - name: NAMESPACE
      value: "default"
    workspaces:
    - name: kubeconfig-dir
      workspace: kubeconfig-dir
    - name: manifest-dir
      workspace: pipeline-shared-data
---

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tekton-pipelinerun
spec:
  pipelineRef:
    name: tekton-pipeline
  serviceAccountName: tekton-sa
  workspaces:
  - name: pipeline-shared-data
    persistentvolumeclaim:
      claimName: task-pv-claim
  - name: kubeconfig-dir
    configMap:
      name: k8s-kubeconfig
