apiVersion: v1
kind: Secret
metadata:
	name: git-credential
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: "mysql"
  password: "mysql"

---
apiVersion: v1
kind: Secret
metadata:
 name: docker-credential
 annotations:
   tekton.dev/docker-0: https://index.docker.io
type: kubernetes.io/basic-auth
stringData:
  username: "mysql"
  password: "mysql" 

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
secrets:
  - name: git-credential
  - name: docker-credential
