apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      drop[0]: YOUR_VALUE
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
        - containerPort: 50000