# mysql-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb-mysql
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydb-mysql
  template:
    metadata:
      labels:
        app: mydb-mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/bitnami/mysql:8.0.35-debian-11-r0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mydb-mysql
              key: mysql-root-password
        ports:
        - containerPort: 3306
          name: mysql