# mysql-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: mydb-mysql
  namespace: default
spec:
  selector:
    app: mydb-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
